build: Bump!
* Kernel 5.0.12
* Update isl tar .21
* GNU GCC 9.1.0 Released
* GNU GCC 10.0.0 Experimental
* Add option to specify the amount of jobs

Signed-off-by: najahiiii <tlogitechnjhi@gmail.com>

diff --git a/build b/build
--- a/build
+++ b/build
@@ -42,15 +42,18 @@ function help_menu() {
     echo
     echo "${BOLD}USAGE:${RST} ${0} <options>"
     echo
-    echo "${BOLD}EXAMPLE:${RST} ${0} -a arm64 -s linaro -v 7"
+    echo "${BOLD}EXAMPLE:${RST} ${0} -a arm64 -s linaro -v 8"
+    echo
+    echo "${BOLD}EXAMPLE:${RST} ${0} -a x86_64 -s gnu -v 8"
     echo
     echo "${BOLD}REQUIRED PARAMETERS:${RST}"
     echo "  -a  | --arch:        Possible values: arm, arm64, i686, or x86_64. This is the toolchain's target architecture."
     echo "  -s  | --source:      Possible values: gnu or linaro. This is the GCC source (GNU official vs. Linaro fork)."
-    echo "  -v  | --version:     Possible values: (4, 5, 6, 7, 8, and 9* [*GNU only]). This is the GCC version to build."
+    echo "  -v  | --version:     Possible values: (4, 5, 6, 7, 8, 9*, and 10* [*GNU only]). This is the GCC version to build."
     echo
     echo "${BOLD}OPTIONAL PARAMETERS:${RST}"
     echo "  -f  | --full-src:    Download full git repos instead of shallow clones"
+    echo "  -j  | --jobs:        Specify the amount of threads to use. This overrides the default automatic detection"
     echo "  -nu | --no-update:   Do not update the downloaded components before building (useful if you have slow internet)."
     echo "  -p  | --package:     Possible values: gz or xz. Compresses toolchain after build."
     echo "  -tm | --tmpfs:       Use tmpfs for building (useful if you have much RAM)."
@@ -194,10 +197,10 @@ function setup_variables() {
     MPC_git="master"
     MPC_tar="mpc-1.1.0"
     ISL_git="master"
-    ISL_tar="isl-0.20"
+    ISL_tar="isl-0.21"
     GLIBC_git="master"
     GLIBC_tar="glibc-2.29"
-    LINUX="5.0"
+    LINUX="5.0.12"
 
     # Start of script
     START=$(date +%s)
@@ -215,6 +218,7 @@ function parse_parameters() {
 
             # OPTIONAL FLAGS
             "-f"|"--full-src") FULL_SOURCE=true ;;
+            "-j"|"--jobs") shift && JOBS=-j${1} ;;
             "-nu"|"--no-update") NO_UPDATE=true ;;
             "-p"|"--package") shift && COMPRESSION=${1} ;;
             "-tm"|"--tmpfs") TMPFS=true ;;
@@ -258,7 +262,8 @@ function parse_parameters() {
             "gnu:6") GCC=gcc-6-branch ;;
             "gnu:7") GCC=gcc-7-branch ;;
             "gnu:8") GCC=gcc-8-branch ;;
-            "gnu:9") GCC=master ;;
+            "gnu:9") GCC=gcc-9-branch ;;
+            "gnu:10") GCC=master ;;
             "linaro:4") GCC=linaro-local/releases/linaro-4.9-2017.01
                         GLIBC_git="release/2.27/master"
                         ISL_git="isl-0.17.1" ;;
@@ -270,6 +275,7 @@ function parse_parameters() {
             # ARM has taken the responsibility from Linaro since 8.x
             "linaro:8") GCC=linaro-local/ARM/arm-8-branch ;;
             "linaro:9") die "There's no such thing as Linaro 9.x Clannad..." -h ;;
+            "linaro:10") die "There's no such thing as Linaro 9.x Clannad..." -h ;;
             *) die "Absent or invalid GCC version or source specified!" -h ;;
         esac
     else
@@ -286,7 +292,8 @@ function parse_parameters() {
             "gnu:6") GCC=gcc-6.5.0 ;;
             "gnu:7") GCC=gcc-7.4.0 ;;
             "gnu:8") GCC=gcc-8.3.0 ;;
-            "gnu:9") die "GCC 9.0 is currently a WIP so there is no tarball to download! Either use the git repo or choose a new version..." ;;
+            "gnu:9") GCC=gcc-9.1.0 ;;
+            "gnu:10") die "GCC 10.0.0 is currently a WIP so there is no tarball to download! Either use the git repo or choose a new version..." ;;
             "linaro:4") GCC=linaro-4.9-2017.01
                         GLIBC_tar="glibc-2.27"
                         ISL_tar="isl-0.17.1" ;;
@@ -299,6 +306,7 @@ function parse_parameters() {
             # See later in this script why it's defined like this
             "linaro:8") GCC=8.3-2019.03 ;;
             "linaro:9") die "There's no such thing as Linaro 9.x Clannad..." -h ;;
+            "linaro:10") die "There's no such thing as Linaro 10.x Clannad..." -h ;;
             *) die "Absent or invalid GCC version or source specified!" -h ;;
         esac
     fi
@@ -353,7 +361,7 @@ function build_binaries() {
         [[ ! -d ${PIGZ} ]] && git -C "$(dirname "${PIGZ}")" clone --depth=1 https://github.com/madler/pigz
         git -C "${PIGZ}" clean -fxdq
         git -C "${PIGZ}" pull
-        make -C "${PIGZ}" ${JOBS} pigz || die "Error building pigz!"
+        make -C "${PIGZ}" "${JOBS}" pigz || die "Error building pigz!"
         mv "${PIGZ}"/pigz "${PREBUILTS_BIN}"
     fi
 
@@ -362,7 +370,7 @@ function build_binaries() {
         [[ ! -d ${PXZ} ]] && git -C "$(dirname "${PXZ}")" clone --depth=1 https://github.com/jnovy/pxz
         git -C "${PXZ}" clean -fxdq
         git -C "${PXZ}" pull
-        make -C "${PXZ}" ${JOBS} pxz || die "Error building pxz!"
+        make -C "${PXZ}" "${JOBS}" pxz || die "Error building pxz!"
         mv "${PXZ}"/pxz "${PREBUILTS_BIN}"
     fi
 
@@ -375,8 +383,8 @@ function build_binaries() {
             (
                 cd "${LZLIB}" || die "Issue with extracting lzlib source!"
                 ./configure --prefix="$(dirname "${PREBUILTS_BIN}")"
-                make ${JOBS} || die "Error building lzlib!"
-                make install ${JOBS} || die "Error installing lzlib!"
+                make "${JOBS}" || die "Error building lzlib!"
+                make install "${JOBS}" || die "Error installing lzlib!"
             )
         )
     fi
@@ -390,8 +398,8 @@ function build_binaries() {
             (
                 cd ${PLZIP} || die "Issue with extracting plzip source!"
                 ./configure --prefix="$(dirname "${PREBUILTS_BIN}")" CXXFLAGS="-Wall -W -O2 -I$(dirname "${PREBUILTS_BIN}")/include -L$(dirname "${PREBUILTS_BIN}")/lib"
-                make ${JOBS} || die "Error building plzip!"
-                make install ${JOBS} || die "Error installing plzip!"
+                make "${JOBS}" || die "Error building plzip!"
+                make install "${JOBS}" || die "Error installing plzip!"
             )
         )
     fi
@@ -660,8 +668,8 @@ function build_binutils() {
                           --disable-gdb \
                           --enable-gold \
                           "${CONFIGURATION[@]}"
-    make ${JOBS} || die "Error while building binutils!" -n
-    make install ${JOBS} || die "Error while installing binutils!" -n
+    make "${JOBS}" || die "Error while building binutils!" -n
+    make install "${JOBS}" || die "Error while installing binutils!" -n
 }
 
 
@@ -671,7 +679,7 @@ function build_headers() {
     cd ../linux || die "Linux kernel folder does not exist!"
     make ARCH="${KERNEL_ARCH}" \
         INSTALL_HDR_PATH="${INSTALL}/${TARGET}" \
-        headers_install ${JOBS} || die "Error while building/installing Linux headers!" -n
+        headers_install "${JOBS}" || die "Error while building/installing Linux headers!" -n
 }
 
 
@@ -683,11 +691,11 @@ function build_gcc() {
                      --target=${TARGET} \
                      --prefix="${INSTALL}" \
                      "${CONFIGURATION[@]}"
-    make all-gcc ${JOBS} || die "Error while building gcc!" -n
-    make install-gcc ${JOBS} || die "Error while installing gcc!" -n
+    make all-gcc "${JOBS}" || die "Error while building gcc!" -n
+    make install-gcc "${JOBS}" || die "Error while installing gcc!" -n
     if [[ ${ARCH} = "x86_64" ]]; then
-        make all-target-libgcc ${JOBS} || die "Error while installing libgcc for host!" -n
-        make install-target-libgcc ${JOBS} || die "Error while installing libgcc for target!" -n
+        make all-target-libgcc "${JOBS}" || die "Error while installing libgcc for host!" -n
+        make install-target-libgcc "${JOBS}" || die "Error while installing libgcc for target!" -n
     fi
 }
 
@@ -704,22 +712,22 @@ function build_glibc() {
                           --target=${TARGET} \
                           --with-headers="${INSTALL}/${TARGET}/include" \
                           "${CONFIGURATION[@]}" libc_cv_forced_unwind=yes
-    make install-bootstrap-headers=yes install-headers ${JOBS} || die "Error installing headers for glibc!" -n
-    make csu/subdir_lib ${JOBS} || die "Error while making subdir_lib for glibc!" -n
+    make install-bootstrap-headers=yes install-headers "${JOBS}" || die "Error installing headers for glibc!" -n
+    make csu/subdir_lib "${JOBS}" || die "Error while making subdir_lib for glibc!" -n
     install csu/crt1.o csu/crti.o csu/crtn.o "${INSTALL}/${TARGET}/lib"
     ${TARGET}-gcc -nostdlib -nostartfiles -shared -x c /dev/null -o "${INSTALL}/${TARGET}/lib/libc.so"
     touch "${INSTALL}/${TARGET}/include/gnu/stubs.h"
     if [[ ${ARCH} = "x86_64" ]]; then
-        make ${JOBS} || die "Error while building glibc for the host!" -n
-        make install ${JOBS} || die "Error while installing glibc for the host!" -n
+        make "${JOBS}" || die "Error while building glibc for the host!" -n
+        make install "${JOBS}" || die "Error while installing glibc for the host!" -n
     else
         cd ../build-gcc || die "GCC build folder does not exist!"
-        make all-target-libgcc ${JOBS} || die "Error while building libgcc for target!" -n
-        make install-target-libgcc ${JOBS} || die "Error while installing libgcc for target!" -n
+        make all-target-libgcc "${JOBS}" || die "Error while building libgcc for target!" -n
+        make install-target-libgcc "${JOBS}" || die "Error while installing libgcc for target!" -n
 
         cd ../build-glibc || die "glibc build folder does not exist!"
-        make ${JOBS} || die "Error while building glibc for target" -n
-        make install ${JOBS} || die "Error while installing glibc for target" -n
+        make "${JOBS}" || die "Error while building glibc for target" -n
+        make install "${JOBS}" || die "Error while installing glibc for target" -n
     fi
 }
 
@@ -728,8 +736,8 @@ function build_glibc() {
 function install_gcc() {
     header "INSTALLING GCC"
     cd ../build-gcc || die "GCC build folder does not exist!"
-    make all ${JOBS} || die "Error while compiling final toolchain!" -n
-    make install ${JOBS} || die "Error while installing final toolchain!" -n
+    make all "${JOBS}" || die "Error while compiling final toolchain!" -n
+    make install "${JOBS}" || die "Error while installing final toolchain!" -n
     cd ..
 }
 
